censo/config/routes.rb
Rails.application.routes.draw do
  
  get 'personas/sexcount' => 'personas#sex_count', defaults: {format: :json}

  resources :personas

end

censo/app/models/persona.rb
class Persona < ActiveRecord::Base
end

censo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

censo/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  before_action :set_default_response_format, only: [:sex_count]
  before_action :delete_cache, only: [:destroy, :create, :update]

  #Definitely not the best idea.
  @@males = nil
  @@females = nil

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all.limit(1000)
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  def sex_count
    if not (@@males and @@females)
      count = Persona.group(:P02).count
      @@males = count[1]
      @@females = count[2]
    end
    respond_to do |format|
      msg = [{:label => "Males", :value => @@males}, {:label => "Females", :value => @@females}]
      format.json  { render :json => msg }
    end
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)
    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:PERSONA_REF_ID, :HOGAR_REF_ID, :P01, :P02, :P03, :P05, :P06, :P07, :P12, :ADADAGRU, :EDADQUI, :P08, :P09, :P10, :CONDACT)
    end

    def set_default_response_format
      request.format = :json
    end

    def delete_cache
      @@males = nil
      @@females = nil
    end
end

censo/app/helpers/application_helper.rb
module ApplicationHelper
end

censo/app/helpers/personas_helper.rb
module PersonasHelper
end

censo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Censo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

censo/app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :HOGAR_REF_ID %><br>
    <%= f.text_field :HOGAR_REF_ID %>
  </div>
  <div class="field">
    <%= f.label :P01 %><br>
    <%= f.text_field :P01 %>
  </div>
  <div class="field">
    <%= f.label :P02 %><br>
    <%= f.text_field :P02 %>
  </div>
  <div class="field">
    <%= f.label :P03 %><br>
    <%= f.text_field :P03 %>
  </div>
  <div class="field">
    <%= f.label :P05 %><br>
    <%= f.text_field :P05 %>
  </div>
  <div class="field">
    <%= f.label :P06 %><br>
    <%= f.text_field :P06 %>
  </div>
  <div class="field">
    <%= f.label :P07 %><br>
    <%= f.text_field :P07 %>
  </div>
  <div class="field">
    <%= f.label :P12 %><br>
    <%= f.text_field :P12 %>
  </div>
  <div class="field">
    <%= f.label :EDADAGRU %><br>
    <%= f.text_field :EDADAGRU %>
  </div>
  <div class="field">
    <%= f.label :EDADQUI %><br>
    <%= f.text_field :EDADQUI %>
  </div>
  <div class="field">
    <%= f.label :P08 %><br>
    <%= f.text_field :P08 %>
  </div>
  <div class="field">
    <%= f.label :P09 %><br>
    <%= f.text_field :P09 %>
  </div>
  <div class="field">
    <%= f.label :P10 %><br>
    <%= f.text_field :P10 %>
  </div>
  <div class="field">
    <%= f.label :CONDACT %><br>
    <%= f.text_field :CONDACT %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

censo/app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

censo/app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personas</h1>

<table>
  <thead>
    <tr>
      <th>Persona ref id</th>
      <th>Hogar ref id</th>
      <th>P01</th>
      <th>Sexo</th>
      <th>Edad</th>
      <th>P05</th>
      <th>P06</th>
      <th>P07</th>
      <th>P12</th>
      <th>Edadagru</th>
      <th>Edadqui</th>
      <th>P08</th>
      <th>P09</th>
      <th>P10</th>
      <th>Condact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.id %></td>
        <td><%= persona.HOGAR_REF_ID %></td>
        <td><%= persona.P01 %></td>
        <td>
          <% if persona.P02 == 1 %>
            M
          <% elsif persona.P02 == 2 %>
            F
          <% else %>
            <%= persona.P02 %>
          <% end %>
        </td>
        <td><%= persona.P03 %></td>
        <td><%= persona.P05 %></td>
        <td><%= persona.P06 %></td>
        <td><%= persona.P07 %></td>
        <td><%= persona.P12 %></td>
        <td><%= persona.EDADAGRU %></td>
        <td><%= persona.EDADQUI %></td>
        <td><%= persona.P08 %></td>
        <td><%= persona.P09 %></td>
        <td><%= persona.P10 %></td>
        <td><%= persona.CONDACT %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

censo/app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

censo/app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Persona ref id:</strong>
  <%= @persona.id %>
</p>

<p>
  <strong>Hogar ref id:</strong>
  <%= @persona.HOGAR_REF_ID %>
</p>

<p>
  <strong>P01:</strong>
  <%= @persona.P01 %>
</p>

<p>
  <strong>Sexo:</strong>
  <% if @persona.P02 == 1 %>
    M
  <% elsif @persona.P02 == 2 %>
    F
  <% else %>
    <%= @persona.P02 %>
  <% end %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @persona.P03 %>
</p>

<p>
  <strong>P05:</strong>
  <%= @persona.P05 %>
</p>

<p>
  <strong>P06:</strong>
  <%= @persona.P06 %>
</p>

<p>
  <strong>P07:</strong>
  <%= @persona.P07 %>
</p>

<p>
  <strong>P12:</strong>
  <%= @persona.P12 %>
</p>

<p>
  <strong>Edadagru:</strong>
  <%= @persona.EDADAGRU %>
</p>

<p>
  <strong>Edadqui:</strong>
  <%= @persona.EDADQUI %>
</p>

<p>
  <strong>P08:</strong>
  <%= @persona.P08 %>
</p>

<p>
  <strong>P09:</strong>
  <%= @persona.P09 %>
</p>

<p>
  <strong>P10:</strong>
  <%= @persona.P10 %>
</p>

<p>
  <strong>Condact:</strong>
  <%= @persona.CONDACT %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>